# Next.js Frontend Dockerfile
FROM node:20-alpine
WORKDIR /app

# Install dependencies
COPY package.json ./
COPY postcss.config.js ./
COPY tailwind.config.js ./
COPY next.config.js ./
COPY tsconfig.json ./

RUN npm install

# Copy source
COPY src ./src

# Expose port
EXPOSE 3000

# Run in dev mode
CMD ["npm", "run", "dev"]
